# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class BBox(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, northeast: List[float]=None, southwest: List[float]=None):  # noqa: E501
        """BBox - a model defined in Swagger

        :param northeast: The northeast of this BBox.  # noqa: E501
        :type northeast: List[float]
        :param southwest: The southwest of this BBox.  # noqa: E501
        :type southwest: List[float]
        """
        self.swagger_types = {
            'northeast': List[float],
            'southwest': List[float]
        }

        self.attribute_map = {
            'northeast': 'northeast',
            'southwest': 'southwest'
        }

        self._northeast = northeast
        self._southwest = southwest

    @classmethod
    def from_dict(cls, dikt) -> 'BBox':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BBox of this BBox.  # noqa: E501
        :rtype: BBox
        """
        return util.deserialize_model(dikt, cls)

    @property
    def northeast(self) -> List[float]:
        """Gets the northeast of this BBox.


        :return: The northeast of this BBox.
        :rtype: List[float]
        """
        return self._northeast

    @northeast.setter
    def northeast(self, northeast: List[float]):
        """Sets the northeast of this BBox.


        :param northeast: The northeast of this BBox.
        :type northeast: List[float]
        """

        self._northeast = northeast

    @property
    def southwest(self) -> List[float]:
        """Gets the southwest of this BBox.


        :return: The southwest of this BBox.
        :rtype: List[float]
        """
        return self._southwest

    @southwest.setter
    def southwest(self, southwest: List[float]):
        """Sets the southwest of this BBox.


        :param southwest: The southwest of this BBox.
        :type southwest: List[float]
        """

        self._southwest = southwest
