# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.geo_code import GeoCode  # noqa: F401,E501
from swagger_server import util


class GeoCodes(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, list_of_geo_code: List[GeoCode]=None):  # noqa: E501
        """GeoCodes - a model defined in Swagger

        :param list_of_geo_code: The list_of_geo_code of this GeoCodes.  # noqa: E501
        :type list_of_geo_code: List[GeoCode]
        """
        self.swagger_types = {
            'list_of_geo_code': List[GeoCode]
        }

        self.attribute_map = {
            'list_of_geo_code': 'list_of_GeoCode'
        }

        self._list_of_geo_code = list_of_geo_code

    @classmethod
    def from_dict(cls, dikt) -> 'GeoCodes':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GeoCodes of this GeoCodes.  # noqa: E501
        :rtype: GeoCodes
        """
        return util.deserialize_model(dikt, cls)

    @property
    def list_of_geo_code(self) -> List[GeoCode]:
        """Gets the list_of_geo_code of this GeoCodes.


        :return: The list_of_geo_code of this GeoCodes.
        :rtype: List[GeoCode]
        """
        return self._list_of_geo_code

    @list_of_geo_code.setter
    def list_of_geo_code(self, list_of_geo_code: List[GeoCode]):
        """Sets the list_of_geo_code of this GeoCodes.


        :param list_of_geo_code: The list_of_geo_code of this GeoCodes.
        :type list_of_geo_code: List[GeoCode]
        """
        if list_of_geo_code is None:
            raise ValueError("Invalid value for `list_of_geo_code`, must not be `None`")  # noqa: E501

        self._list_of_geo_code = list_of_geo_code
