---
swagger: "2.0"
info:
  description: "Geocoder API"
  version: "1.0.0"
  title: "Geocoder API"
host: "localhost:8080"
basePath: "/geocoder"
schemes:
- "https"
paths:
  /locate:
    get:
      summary: "Get the latitude and longitude of an address"
      description: "Gets an object containing the lattitude and longitude of a street\
        \ address"
      operationId: "get_locate"
      produces:
      - "application/json"
      parameters:
      - name: "address"
        in: "query"
        description: "The address to look up"
        required: false
        type: "string"
      - name: "northeast"
        in: "query"
        required: false
        type: "array"
        items:
          type: "number"
        collectionFormat: "csv"
        maxItems: 2
        minItems: 2
      - name: "southwest"
        in: "query"
        required: false
        type: "array"
        items:
          type: "number"
        collectionFormat: "csv"
        maxItems: 2
        minItems: 2
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/latlong"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
definitions:
  latlong:
    type: "object"
    required:
    - "latitude"
    - "longitude"
    properties:
      latitude:
        type: "number"
      longitude:
        type: "number"
    example:
      latitude: 37.43499200000000115551301860250532627105712890625
      longitude: -122.1305370000000038999132812023162841796875
