---
swagger: "2.0"
info:
  description: "Geocoder API"
  version: "1.0.0"
  title: "Geocoder"
host: "localhost:8080"
basePath: "/geocoder"
schemes:
- "https"
paths:
  /forward:
    get:
      summary: "Forward geocoding"
      description: "Does forward geocoding"
      operationId: "get_forward"
      produces:
      - "application/json"
      parameters:
      - name: "location"
        in: "query"
        description: "A string value of the location you are geocoding. See  https://developers.google.com/maps/faq#geocoder_queryformat\
          \ for reference."
        required: true
        type: "string"
      - name: "region"
        in: "query"
        description: "A 2 letter string value of the region you would like to query,\
          \ see https://developers.google.com/maps/documentation/geocoding/intro#RegionCodes\
          \ for reference."
        required: false
        type: "string"
      - name: "bounds"
        in: "query"
        description: "A string value denoting a bounding box to focus the search within.\
          \ The bounds parameter defines the latitude/longitude coordinates of the\
          \ southwest and northeast corners of this bounding box using a pipe (|)\
          \ character to separate the coordinates. See  https://developers.google.com/maps/documentation/geocoding/intro#Viewports"
        required: false
        type: "array"
        collectionFormat: "pipes"
        items:
          type: "string"
        maxItems: 2
        minItems: 2
      - name: "components"
        in: "query"
        description: "A list of string values specifying component restrictions.
          \ Available filters are postal_code, country, route, locality, administrative_area.\
          \ See https://developers.google.com/maps/documentation/geocoding/intro#ComponentFiltering\
          \ for reference."
        required: false
        type: "array"
        items:
          type: "string"
        collectionFormat: "pipes"
      responses:
        200:
          description: "OK"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
  /reverse:
    get:
      summary: "Reverse geocoding"
      description: "Does reverse geocoding"
      operationId: "get_reverse"
      produces:
      - "application/json"
      parameters:
      - name: "latlong"
        in: "query"
        description: "The latitude/longitude pair to resolve."
        required: true
        type: "string"
      - name: "result_type"
        in: "query"
        description: "An optional set of result_types to retrieve. See https://developers.google.com/maps/documentation/geocoding/intro#reverse-restricted for details"
        required: false
        type: "array"
        items:
          type: "string"
        collectionFormat: "pipes"      
      responses:
        200:
          description: "OK"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
definitions:
  GeoCodes:
    type: "object"
    required:
    - "list_of_GeoCode"
    properties:
      list_of_GeoCode:
        type: "array"
        items:
          $ref: "#/definitions/GeoCode"
  GeoCode:
    type: "object"
    properties:
      accuracy:
        type: "string"
      address:
        type: "string"
      bbox:
        $ref: "#/definitions/BBox"
      city:
        type: "string"
      confidence:
        type: "integer"
      country:
        type: "string"
      county:
        type: "string"
      housenumber:
        type: "string"
      lat:
        type: "number"
      lon:
        type: "number"
      neighborhood:
        type: "string"
      ok:
        type: "boolean"
      place:
        type: "string"
      postal:
        type: "string"
      postal_town:
        type: "string"
      quality:
        type: "string"
      state:
        type: "string"
      status:
        type: "string"
      street:
        type: "string"
      sublocality:
        type: "string"
      subpremise:
        type: "string"
  BBox:
    type: "object"
    properties:
      northeast:
        type: "array"
        items:
          type: "number"
          description: "array of [latitude, longitude]"
      southwest:
        type: "array"
        items:
          type: "number"
          description: "array of [latitude, longitude]"
  Error:
    type: "object"
    required:
    - "detail"
    - "status"
    - "title"
    - "type"
    properties:
      detail:
        type: "string"
      status:
        type: "integer"
      title:
        type: "string"
      type:
        type: "string"
