---
swagger: "2.0"
info:
  description: "Geocoder API"
  version: "1.0.0"
  title: "Geocoder API"
host: "localhost:8080"
basePath: "/geocoder"
schemes:
- "https"
paths:
  /locate:
    get:
      summary: "Get the latitude and longitude of an address"
      description: "Gets an object containing the lattitude and longitude of a street address"
      operationId: "get_latitude"
      produces:
      - "application/json"
      parameters: 
        - in: query
          name: address
          type: string
          description: The address to look up
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/latlong"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"  
definitions:
  latlong:
    type: "object"
    required:
    - "latitude"
    - "longitude"
    properties:
      latitude:
        type: "number"
      longitude:
        type: "number"
    example:
      latitude: 37.434992
      longitude: -122.130537
